version: "3.8"

services:
  document-processor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "0"
      API_ENDPOINT: "http://document-understanding.rased.io/v1/document-verification"
      API_KEY: "${API_KEY}"
    command: >
      bash -lc "gunicorn run:app --workers ${WORKERS:-2} --timeout ${TIMEOUT:-60}
      --bind 0.0.0.0:$PORT"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os,urllib.request,sys; sys.exit(0) if urllib.request.urlopen(f'http://127.0.0.1:{os.getenv('PORT','8000')}/health').getcode()==200 else sys.exit(1)\""]
      interval: 30s
      timeout: 10s
      retries: 3
