version: "3.8"

services:
  document-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "0"
      API_ENDPOINT: "http://document-understanding.rased.io/v1/document-verification"
      API_KEY: "${API_KEY}"
      PORT: 8000
    command: >
      bash -lc "gunicorn app:app --workers ${WORKERS:-2} --timeout ${TIMEOUT:-60}
      --bind 0.0.0.0:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
